
networks:
  multi_nodes_localnet:
    external: true  # Referencing an existing network

services:
  tx-bot1:
    image: evmos/tx-bot-dev
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: tx-bot1
    networks:
      - multi_nodes_localnet
    volumes:
      - ./build/node0/key_priv.hex:/tmp/key_priv.hex
    entrypoint: ["sh", "-c", "export ORCH_PRIV_KEY=$(cat /tmp/key_priv.hex) && node ./dist/index.js"]
    environment:
      - RPC_URL=http://node0:8545
      - API_URL=http://node0:1317
      - LOG_LEVEL=info
      - NUMBER_OF_WORKERS=2
      - WORKER_TYPES=gasConsumer,ethSender
      #- WORKER_TYPES=bank,delegate,gasConsumer,converter,ethSender
    restart: always